name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
categories:
  - title: "💥 Breaking Change 💥"
    labels:
      - "breaking-change"
    exclusive: true
  - title: "⚡ Enhancements ⚡"
    labels:
      - "enhancement"
    exclusive: true
  - title: "✨ New Features ✨"
    labels:
      - "feature"
    exclusive: true
  - title: "🐛 Bug Fixes 🐛"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
    exclusive: true
  - title: "🎨 Styling 🎨"
    labels:
      - "style"
    exclusive: true    
  - title: "🔩 Dependency 🔩"
    labels:
      - "dependencies"
    collapse-after: 1
    exclusive: true
  - title: "🔧 Maintenance 🔧"
    labels:
      - "chore"
      - "ci"
    collapse-after: 1
    exclusive: true
  - title: "🎓 Code Quality 🎓"
    labels:
      - "code-quality"
    exclusive: true
  - title: "📝 Documentation 📝"
    labels:
      - "documentation"
    collapse-after: 1
    exclusive: true

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/firstof9/ha-appliance-card/$RESOLVED_VERSION/total.svg)](https://github.com/firstof9/ha-appliance-card/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/firstof9/ha-appliance-card/issues)

autolabeler:
  - label: 'feature'
    title:
      - '^feat'
      - '^feat:'
      - '^feat\('
  - label: 'bugfix'
    title:
      - '^fix'
      - '^fix:'
      - '^fix\('
  - label: 'chore'
    title:
      - '^chore'
      - '^chore:'
      - '^chore\('
  - label: 'ci'
    title:
      - '^ci'
      - '^ci:'
      - '^ci\('
    files:
      - '.github/**/*'
  - label: 'style'
    title:
      - '^style'
      - '^style:'
      - '^style\('
    files:
      - 'src/styles/**/*'
  - label: 'documentation'
    title:
      - '^docs'
      - '^docs:'
      - '^docs\('
    files:
      - 'README.md'
      - 'images/**/*'
      - 'screenshots/**/*'
  - label: 'enhancement'
    title:
      - '^refactor'
      - '^refactor:'
      - '^refactor\('
  - label: 'code-quality'
    title:
      - '^tests'
      - '^test'
      - '^test:'
    files:
      - 'test/**/*'
  - label: 'dependencies'
    title:
      - '^build\(deps\)'
      - '^chore\(deps\)'


